language: c++
sudo: false
dist: trusty
addons:
  apt:
    packages:
    - libfreetype6-dev
    - libsdl2-dev
before_script:
- |
    if [ ! -x ~/ddnet-libs ]; then
      git clone https://github.com/ddnet/ddnet-libs ~/ddnet-libs/
    fi
script:
- ln -s ~/ddnet-libs/ ddnet-libs
- cd ddnet-libs; git pull; cd ..
- mkdir build
- cd build
- cmake ..
- make everything
env:
  global:
  - CFLAGS="-Wdeclaration-after-statement -Werror"
  - CXXFLAGS="-Werror"
